env:
  - RUNTESTS=True
  - PUBLISHMETA=True
  - PUBLISHDOCS=True
  - TARGET=CC3D
  - TARGET=CC3D OPBL=yes
  - TARGET=CHEBUZZF3
  - TARGET=CJMCU
  - TARGET=EUSTM32F103RC
  - TARGET=SPRACINGF3
  - TARGET=NAZE
  - TARGET=NAZE32PRO
  - TARGET=OLIMEXINO
  - TARGET=PORT103R
  - TARGET=SPARKY
  - TARGET=STM32F3DISCOVERY
  - TARGET=ALIENWIIF1
  - TARGET=ALIENWIIF3

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

# Also build the unit tests with GCC.
matrix:
  include:
    - compiler: gcc
      env: RUNTESTS=True

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi

before_script: arm-none-eabi-gcc --version
script: ./.travis.sh

cache: apt

notifications:
  irc: "chat.freenode.net#cleanflight"
  use_notice: true
  skip_join: true